# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

global:
  scrape_interval: 1s  # Default is 15s; reduce it to speed up data collection
  evaluation_interval: 1s  # Evaluate rules every 1 second

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - vision_edge_ai:8082

