# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-video-analytics
    container_name: ai-video-analytics
    restart: always
    privileged: true
    group_add:
      - ${RENDER_GROUP_ID:-110}
    ipc: host
    network_mode: host
    environment:
      - DEVICE=${DEVICE:-CPU}
    devices:
      - /dev:/dev:rw
      - /lib/modules:/lib/modules:rw
    volumes:
      - datadb:/usr/src/app/data:rw

volumes:
  datadb:

