name: "Feature/Enhancement Suggestion"
description: "I am suggesting new features or enhancements"
title: "[Suggestion]"
labels:
  - "enhancement"
  - "triage"
body:
  - type: dropdown
    id: user
    attributes:
      label: Target User
      description: Who will be use this feature
      options:
        - "Contributor: the developer of the repo i.e. CASE CSE"
        - "OxM: board vendor"
        - "Developer: consumer that purchase a board and want to proceed with development"
      multiple: true
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description:  Provide a clear and concise description of the new feature or enhancement you are suggesting.
      placeholder: Please describe the suggested feature or enhancement.
  - type: textarea
    attributes:
      label: Justification
      description: Describe why this enhancement is needed
      placeholder: Please list the benefits
  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior or limitations that this suggestion aims to address.
      placeholder: Please describe the current behavior or limitations.
